server:
  port: ${SERVER.PORT:8761}
spring:
  application:
    name: ${SPRING.APPLICATION.NAME:eureka-server}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE:http://localhost:8761/eureka,https://library.kouleen.cn/eureka}
    register-with-eureka: ${EUREKA.CLIENT.REGISTER-WITH-EUREKA:true}
  instance:
    prefer-ip-address: ${EUREKA.INSTANCE.PREFER-IP-ADDRESS:true}
    lease-expiration-duration-in-seconds: ${EUREKA.INSTANCE.LEASE-EXPIRATION-DURATION-IN-SECONDS:30}
    lease-renewal-interval-in-seconds: ${EUREKA.INSTANCE.LEASE-RENEWAL-INTERVAL-IN-SECONDS:10}
  server:
    response-cache-auto-expiration-in-seconds: ${EUREKA.SERVER.RESPONSE-CACHE-AUTO-EXPIRATION-IN-SECONDS:30}
management:
  endpoints:
    web:
      exposure:
        include: '*'

